uploads = []
generated = []

[[outputs]]
id = "oAqWlowljLq9Y6GpLXSMg"
uri = "file://exam_solution/Arasinav_Cevap.pdf"
type = "pdf"
title = "Ara Sınav Cevap Belgesi (sınıf diyagramları yatay sayfada)"
